### ISSUE TITLE
MFi auth not supported. Falling back to HAP_MFI_AUTH_NONE

### ISSUE THREAD

**Issue by jakenzhu** [katadelos/micropython-esp32-homekit#1]
when it run,I get "MFi auth not supported. Falling back to HAP_MFI_AUTH_NONE"
pls tell me how to do?

**Comment by katadelos** [comment]
This project uses the open source variant of `esp-homekit-sdk`, which does not provide support for MFi features (as noted in the [README](https://github.com/espressif/esp-homekit-sdk/blob/master/README.md) for that project). If you require these features for your project, you will need to contact Espressif directly to obtain access to the MFi variant of their SDK.
